### ISSUE TITLE
Spicord stopped working

### ISSUE THREAD

**Issue by jotapedroefe** [OopsieWoopsie/Spicord#11]
Hello, yesterday spicord just stopped working on my server, only addon i use is the spicord players, but the bot just does not respond to the command now, i started the plugin on a complete new bungee test server and made the config and got the same error there: 
`[10:24:10 INFO]: [JDA] [INFO] Login Successful!`
`[10:24:11 INFO]: [JDA] [INFO] Connected to WebSocket`
`[10:24:11 INFO]: [JDA] [ERROR] Got an unexpected error. Please redirect following message to the devs:`
`[10:24:11 INFO]:        GUILD_CREATE -> {}`
My discord members are sad they cant see who is on the server please try to see whats the issue! Thanks

**Comment by OopsieWoopsie** [comment]
Hi, that's a JDA issue, not Spicord, but anyways I think I can help you with that.
I will need you to answer the following questions to help me out finding the issue.

Do you have any other plugin that includes JDA, or in other words, do you have any other plugin that provides some kind of "Discord feature"?
Is your Discord server "special"? By special I mean if you have upgraded your server to Community or if you have a channel of the type "Announcement", or if your server has other feature that's new on Discord and therefore not implemented in JDA.

If both answers are "no", I would like to see a clean startup log of your server, starting from the initial server messages and ending in the error you reported.

**Comment by jotapedroefe** [comment]
Hello, i did upgrade my server to a community server, and i do use jda with discordsrv and another 1 plugin on bungeecord and all of them work just fine

**Comment by OopsieWoopsie** [comment]
I have just tested Spicord with a Community server and an Announcement channel, I only got an error when upgrading a channel from Text to Announcement, but the bot started without any issue.

Can you send me the log I asked? don't forget to set "debug" to true in the configuration.

**Comment by jotapedroefe** [comment]
Here are the startup logs, and me trying to start and stop the bot: https://pastebin.com/U832xw0m

**Comment by OopsieWoopsie** [comment]
You are using the old 2.6.0 version of Spicord, use the latest.
https://github.com/OopsieWoopsie/Spicord/releases/tag/3.0.0-SNAPSHOT
Choose 3.0.2, it has some extra fixes.

**Comment by jotapedroefe** [comment]
The new versions do not have any config file anywhere how am i suppose to use them?

**Comment by OopsieWoopsie** [comment]
It has a config.toml file that's automatically created when the plugin runs, try deleting the old config, maybe that will help

**Comment by jotapedroefe** [comment]
Ok, it did not generate the config file at the first startup, it only got the lib folder, but a second restart on the network generated the config file, thanks for the help!
