### ISSUE TITLE
Cant get the api working with maven

### ISSUE THREAD

**Issue by RaikasCoding** [OopsieWoopsie/Spicord#13]
the normal depency that is in the readme doesnt work, and LATEST breaks all maven projects? what to do

**Comment by OopsieWoopsie** [comment]
3.1.0 is not released yet and thus not deployed to the repo, the code of the master branch is stable, and its version is 3.1.0, you can try using 3.0.0

```xml
<dependency>
    <groupId>eu.mcdb</groupId>
    <artifactId>spicord-common</artifactId>
    <version>3.0.0-SNAPSHOT</version>
</dependency>
```

**Comment by OopsieWoopsie** [comment]
3.1.0 is now available on the repo.
