### ISSUE TITLE
[Question] Channel Listener

### ISSUE THREAD

**Issue by TrueMB** [OopsieWoopsie/Spicord#14]
Hey,

first of all, thanks for this awesome and easy to handle Plugin!
I managed to do my commands, sending messages, and all that stuff. Works perfect.

But I couldnt find any way to create a listener for a Channel. I want to catch a message in a specific channel to use that one for more stuff. Like Chat filtering, sync and all that stuff.

Is there already something that I missed or is it maybe planed for the future?

**Comment by OopsieWoopsie** [comment]
You can get the JDA instance by using DiscordBot#getJda() so you can do a lot more stuff ^^
For example to listen for messages you can use this example:

```java
public class MessageListener extends ListenerAdapter {

    @Override
    public void onMessageReceived(MessageReceivedEvent event) {
        String channelId = event.getChannel().getId();
        // TODO: check if this is the channel you want

        String message = event.getMessage().getContentDisplay();
        System.out.println(message);
    }
}
```
and then register the listener using:
```java
DiscordBot bot = ...
bot.getJda().addEventListener(new MessageListener());
```

**Comment by TrueMB** [comment]
As I thought: You are Legend!
Thanks for the helpful answer and an awesome day!
