### ISSUE TITLE
Discord invite in README expired

### ISSUE THREAD

**Issue by soccermitchy** [OopsieWoopsie/Spicord#15]
Hey, I'm working on a plugin that uses Spicord, and having some issues I wanted to ask about, but the Discord invite link in the `README.md` expired. Could you generate a new one and update the readme?

**Comment by OopsieWoopsie** [comment]
The invite didn't expired, it was revoked (like all other invites), I plan to make some changes to the server before making it public again, but... as you asked: https://discord.gg/vy2WhM (will expire in 24h)
