### ISSUE TITLE
IntelliJ IDEA

### ISSUE THREAD

**Issue by Sususiwa** [OopsieWoopsie/Spicord#3]
How do I add this into IntelliJ so I can use it?

**Comment by OopsieWoopsie** [comment]
Hey, do you want to add it as a library or do you want to import the source code?

**Comment by Sususiwa** [comment]
I just need to add it as a library to make my own addons.

**Comment by OopsieWoopsie** [comment]
https://stackoverflow.com/questions/1051640/correct-way-to-add-external-jars-lib-jar-to-an-intellij-idea-project
