### ISSUE TITLE
[Suggestion] rank/role linking

### ISSUE THREAD

**Issue by MayhemBill** [OopsieWoopsie/Spicord#41]
Title says it all, link accounts to discord similar to DiscordSRV

**Comment by OopsieWoopsie** [comment]
Hi, that already exists https://www.spigotmc.org/resources/discordrewards.72399/
It is a linking and rewarding plugin :)

**Comment by MayhemBill** [comment]
can it link multiple roles though? that seems to only link a single role

**Comment by OopsieWoopsie** [comment]
> can it link multiple roles though? that seems to only link a single role

This is not about linking/syncing roles, it is for linking minecraft accounts with discord accounts, and I don't plan to make any role syncing addon as that would be a very shitty thing for any server owner to use or implement.
