### ISSUE TITLE
Where to get "daily_statistics" addon

### ISSUE THREAD

**Issue by ZeroG-Network** [OopsieWoopsie/Spicord#43]
Hello

I wanted to know where i can get the Addon for [DailyStatistics for Discord](https://www.spigotmc.org/resources/dailystatistics-for-discord.72421/), cause i would have asked on the discord but the discord link not working to either webpages. 

Kind Regards
MrWhiteFlamesYT
ZeroG Network Co-Owner

**Comment by OopsieWoopsie** [comment]
Just click "Download Now" on the link you sent...

**Comment by greendoescode** [comment]
I cant get to the link provided because ive not got perms, please may you send a link for a github or smthing

**Comment by OopsieWoopsie** [comment]
@GreenDiscord 
https://github.com/Spicord/DailyStatistics/releases/tag/unofficial-1.2

**Comment by greendoescode** [comment]
I've installed, found it in the end! can you answer my other issues thing?
