### ISSUE TITLE
i can't use

### ISSUE THREAD

**Issue by tacgamingproyt** [OopsieWoopsie/Spicord#48]
why i can't bot plss see https://mclo.gs/9XkgtJ2

**Comment by OopsieWoopsie** [comment]
> Line 379 >> [15:06:52] [Server thread/INFO]: [Spicord] Loaded 1 bots, 1 disabled.

> Line 1521 >> [15:09:22] [Server thread/WARN]: [Spicord] Bot 'SERVER LIVE CHAT' is disabled. Skipping.

You didn't followed the most easier step, which is to turn the "enabled" option to "true" in the config.
