### ISSUE TITLE
Bots not starting on Velocity

### ISSUE THREAD

**Issue by RealTriassic** [OopsieWoopsie/Spicord#49]
Title explains itsself.

**Comment by OopsieWoopsie** [comment]
Hi, I'm alreay aware of this as there's no Discord server anymore, I will probably update it or remove it in some weeks, thanks for reporting it tho :smile:

**Comment by RealTriassic** [comment]
> Hi, I'm alreay aware of this as there's no Discord server anymore, I will probably update it or remove it in some weeks, thanks for reporting it tho 😄

How can I receive support then? I have an issue running the plugin on Velocity.

**Comment by OopsieWoopsie** [comment]
> How can I receive support then? I have an issue running the plugin on Velocity.

For support you can create issues on the GitHub repo, I assume you already know how to do it :thinking:

**Comment by RealTriassic** [comment]
> > How can I receive support then? I have an issue running the plugin on Velocity.
> 
> For support you can create issues on the GitHub repo, I assume you already know how to do it 🤔

It'd be easier to get support over Discord, but okay.

I am having an issue on running the plugin on Velocity, the bots just appear as "Starting" and never actually start. No errors get thrown in console, even when in debug mode. The configuration is correct and I have even tried using the default configuration, it did not work.

**Comment by OopsieWoopsie** [comment]
> It'd be easier to get support over Discord, but okay.

Actually I'm more active on GitHub than Discord.

> I am having an issue on running the plugin on Velocity, the bots just appear as "Starting" and never actually start. No errors get thrown in console, even when in debug mode. The configuration is correct and I have even tried using the default configuration, it did not work.

Have you enabled the required "Gateway Intents" for your bot?

**Comment by RealTriassic** [comment]
> > It'd be easier to get support over Discord, but okay.
> 
> Actually I'm more active on GitHub than Discord.
> 
> > I am having an issue on running the plugin on Velocity, the bots just appear as "Starting" and never actually start. No errors get thrown in console, even when in debug mode. The configuration is correct and I have even tried using the default configuration, it did not work.
> 
> Have you enabled the required "Gateway Intents" for your bot?

What are the required gateway intents? I just went ahead and enabled all of them.

**Comment by OopsieWoopsie** [comment]
Did that solved the problem?

**Comment by RealTriassic** [comment]
> Did that solved the problem?

No

**Comment by RealTriassic** [comment]
> > Did that solved the problem?
> 
> No

So is there anything we could do about this?

**Comment by OopsieWoopsie** [comment]
> So is there anything we could do about this?

I suggest you to create a new issue, instead of using this closed issue that was not related to the problem you had in the first place.

I would like you to send me your full server startup log.

**Comment by RealTriassic** [comment]
> > So is there anything we could do about this?
> 
> I suggest you to create a new issue, instead of using this closed issue that was not related to the problem you had in the first place.
> 
> I would like you to send me your full server startup log.

The issue is that there isn't anything out of ordinary in the startup logs, no errors, no warnings, nothing.

**Comment by RealTriassic** [comment]
<img width="611" alt="Screen_Shot_2021-11-06_at_3 37 56_PM" src="https://user-images.githubusercontent.com/40073455/140622196-8a1695e1-45e4-4447-a2c2-2faf94fe1dd9.png">
This is the closest we get to an "error".

Is this still worth opening a new issue for?

**Comment by OopsieWoopsie** [comment]
Hi, I know you don't see any error, but I still need the full server startup log

**Comment by RealTriassic** [comment]
https://mclo.gs/ZktcjQt

**Comment by OopsieWoopsie** [comment]
> Is this still worth opening a new issue for?

Yes, but you can reopen this issue and change the title if you want.

I have made it to show the actual error when the bot fails to start, apart from the simple "An error ocurred[...]" message

(.jar file is into the .zip file)
[Spicord_4.1.0.zip](https://github.com/Spicord/Spicord/files/7492910/Spicord_4.1.0.zip)

**Comment by RealTriassic** [comment]
https://mclo.gs/LpSbxCM 

this is the new server log, using the Spicord build you just sent me.

**Comment by RealTriassic** [comment]
![image](https://user-images.githubusercontent.com/40073455/140744842-31cbc5cc-29f8-401f-95a3-0261f80fa875.png)

**Comment by OopsieWoopsie** [comment]
Are you sure you are using the version I sent? there should be more error details below that last message

**Comment by RealTriassic** [comment]
> Are you sure you are using the version I sent? there should be more error details below that last message

Yes I am sure

**Comment by OopsieWoopsie** [comment]
Ok, I get it, you are getting the error from 
https://github.com/Spicord/Spicord/blob/development/common/src/main/java/org/spicord/SpicordCommand.java#L145
and not from
https://github.com/Spicord/Spicord/blob/development/common/src/main/java/org/spicord/bot/DiscordBot.java#L142
I got confused because both lines contains the same message :sweat: 

so an exception didn't ocurred, the bot just hangs on "Starting" and there's no error related to it... weird

I tried this version on Velocity 3.0.1 (latest release) and on the 3.1.0 snapshot, worked without issue on both, seems like a problem with your bot or your connection with discord, check if your container has internet access and if there isn't any firewall blocking the outgoing connection
