### ISSUE TITLE
Saw this randomly in console

### ISSUE THREAD

**Issue by Zoro-6191** [OopsieWoopsie/Spicord#52]
![image](https://user-images.githubusercontent.com/52291201/145101914-f2a140f7-5094-4cc4-9230-e64da4601b20.png)

I use [BanAnnouncer](https://www.spigotmc.org/resources/banannouncer-discord.64976/) with Spicord

**Comment by OopsieWoopsie** [comment]
> Hello, if this happens often and randomly this could be because you (or your hosting provider) seem to have a very unstable internet connection, and the connection to the realtime discord api gets unexpectedly terminated and thus causing this error, there's nothing I can do about this, sorry.
The plugin will try to reconnect to the discord api after a disconnection happens, so the plugin should automatically recover from this.


( https://github.com/Spicord/Spicord/issues/46#issuecomment-926210844 )
