### ISSUE TITLE
This error comes every time I close the server.

### ISSUE THREAD

**Issue by Zoro-6191** [OopsieWoopsie/Spicord#53]
![image](https://user-images.githubusercontent.com/52291201/145250980-12d8c6f4-55d5-4a7f-8341-2c7928cf7042.png)

**Comment by OopsieWoopsie** [comment]
Update the plugin: https://github.com/Spicord/Spicord/releases/tag/4.1.1

**Comment by Zoro-6191** [comment]
ah my bad

**Comment by OopsieWoopsie** [comment]
Hello, I recommended you to update to 4.1.1 but it introduced a bug causing some addons to not load :frowning_face: , I have got the bug report some hours ago and released the fix just now, please update to 4.1.2 if you have any problem with any addon https://github.com/Spicord/Spicord/releases/tag/4.1.2
