### ISSUE TITLE
[Spicord]: [JDA:JDA] One of the EventListeners had an uncaught exception

### ISSUE THREAD

**Issue by GeleVla** [OopsieWoopsie/Spicord#58]
When trying to run the -info or -players command with Spicord I get the error down below, included with the logs.
The -plugins command does work.

Logs: https://bin.bloom.host/abawabahit
Config: https://mcpaste.io/5f39703f363f27c2

Using the Spicord on Velocity

**Comment by anvorgesa** [comment]
That's because you restarted Spicord ("sp restart") before it even actually started, breaking those addons instances. Be patient and wait until Spicord loads before thinking on reloading it.
