### ISSUE TITLE
Spicord Error

### ISSUE THREAD

**Issue by Fundryi** [OopsieWoopsie/Spicord#6]
I really dont know whats wrong, it should work. 

`
14:27:06 [INFO] [Spicord] Loaded 1 bots, 0 disabled.
> 14:27:06 [INFO] [Spicord] Registered addon 'Server Information' (spicord::info) by OopsieWoopsie
> 14:27:06 [INFO] [Spicord] Registered addon 'Plugin List' (spicord::plugins) by OopsieWoopsie
> 14:27:06 [INFO] [Spicord] Registered addon 'Player List' (spicord::players) by OopsieWoopsie
> 14:27:06 [INFO] [Spicord] Starting the bots...
> 14:27:06 [INFO] [Spicord] Starting bot 'default'.
> 14:27:06 [SEVERE] Exception in thread "Thread-28"
> 14:27:06 [SEVERE] java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticMDCBinder.getMDCA()Lorg/slf4j/spi/MDCAdapter;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/MDC, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticMDCBinder, have different Class objects for the type org/slf4j/spi/MDCAdapter used in the signature
> 14:27:06 [SEVERE] at org.slf4j.MDC.bwCompatibleGetMDCAdapterFromBinder(MDC.java:99)
> 14:27:06 [SEVERE] at org.slf4j.MDC.<clinit>(MDC.java:108)
> 14:27:06 [SEVERE] at net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:207)
> 14:27:06 [SEVERE] at net.dv8tion.jda.core.JDABuilder.build(JDABuilder.java:913)
> 14:27:06 [SEVERE] at eu.mcdb.spicord.bot.DiscordBot.startBot(DiscordBot.java:105)
> 14:27:06 [SEVERE] at eu.mcdb.spicord.bot.DiscordBotLoader$1.run(DiscordBotLoader.java:40)
> 14:27:06 [SEVERE] at java.lang.Thread.run(Thread.java:748)`

**Comment by OopsieWoopsie** [comment]
Hey, please check if you have two (or more) JDA jar file on the plugins/Spicord/lib folder, if yes please delete both or all the jars inside the folder and run your server again, Spicord will automatically create the file. And if that didnt helped you, let me know and I will see what can I do. 

:*

**Comment by Fundryi** [comment]
There was/is only one .jar in it I deleted it to test if it fixes it, but it didn't :(

`11:11:10 [INFO] [Spicord] Loaded 1 bots, 0 disabled.
> 11:11:10 [INFO] [Spicord] [DEBUG] [Loader] Loaded library 'JDA-3.8.3_460-withDependencies.jar'.
> 11:11:10 [INFO] [Spicord] Registered addon 'Server Information' (spicord::info) by OopsieWoopsie
> 11:11:10 [INFO] [Spicord] Registered addon 'Plugin List' (spicord::plugins) by OopsieWoopsie
> 11:11:10 [INFO] [Spicord] Registered addon 'Player List' (spicord::players) by OopsieWoopsie
> 11:11:10 [INFO] [Spicord] Starting the bots...
> 11:11:10 [INFO] [Spicord] Starting bot 'default'.
> 11:11:10 [SEVERE] Exception in thread "Thread-27"
> 11:11:10 [SEVERE] java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
> 11:11:10 [SEVERE] at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
> 11:11:10 [SEVERE] at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
> 11:11:10 [SEVERE] at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
> 11:11:10 [SEVERE] at net.dv8tion.jda.core.utils.JDALogger.getLog(JDALogger.java:98)
> 11:11:10 [SEVERE] at net.dv8tion.jda.core.entities.impl.JDAImpl.<clinit>(JDAImpl.java:65)
> 11:11:10 [SEVERE] at net.dv8tion.jda.core.JDABuilder.build(JDABuilder.java:890)
> 11:11:10 [SEVERE] at eu.mcdb.spicord.bot.DiscordBot.startBot(DiscordBot.java:105)
> 11:11:10 [SEVERE] at eu.mcdb.spicord.bot.DiscordBotLoader$1.run(DiscordBotLoader.java:40)
> 11:11:10 [SEVERE] at java.lang.Thread.run(Thread.java:748)`

**Comment by OopsieWoopsie** [comment]
What version of BungeeCord and Java are you using? I will try to reproduce the error

**Comment by Fundryi** [comment]
Here:

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

[bungeecord.zip](https://github.com/OopsieWoopsie/Spicord/files/3243755/bungeecord.zip)

**Comment by Fundryi** [comment]
Any news? I would really like to use this Plugin :(
What I tested so far:
Downgrading Java to 8.x - 211  I think.
Updating/Downloading the newest version of Bungeecord.

I still get the same error :(

**Comment by OopsieWoopsie** [comment]
Hey, I didn't tested this, I'm very busy lately.

But now I have read the error and I think it happened because BungeeCord has a built-in SLF4J and it isn't loaded by JDA. I will try to fix this today.

**Comment by OopsieWoopsie** [comment]
Just tested with [BungeeCord #1412](https://ci.md-5.net/job/BungeeCord/1412/) (the same as you are using) and with Spicord 1.0.4-SNAPSHOT (latest public version) and I cannot reproduce the error you are reporting.

> java version "12.0.1" 2019-04-16
> Java(TM) SE Runtime Environment (build 12.0.1+12)
> Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

Anyways, I will change the package of the built-in SLF4J of the JDA jar file.

If you need extra support, you can join our [Discord server](https://discord.gg/fBzAwWW) and talk with me.

**Comment by Fundryi** [comment]
I know you closed it, but would you ever consider adding LiteBans Support :o?

**Comment by OopsieWoopsie** [comment]
Spicord with LiteBans support?
You are on the wrong repo...
See [BanAnnouncer](https://github.com/OopsieWoopsie/BanAnnouncer)

**Comment by OopsieWoopsie** [comment]
It sould be working now. This error was the same as #8
