### ISSUE TITLE
Flushing frames to the server failed: Connection or outbound has closed

### ISSUE THREAD

**Issue by GeleVla** [OopsieWoopsie/Spicord#60]
Warning when user joins that is not whitelisted.

Logs: https://bin.bloom.host/osajefijin

**Comment by anvorgesa** [comment]
> Hello, if this happens often and randomly this could be because you (or your hosting provider) seem to have a very unstable internet connection, and the connection to the realtime discord api gets unexpectedly terminated and thus causing this error, there's nothing I can do about this, sorry.
The plugin will try to reconnect to the discord api after a disconnection happens, so the plugin should automatically recover from this.

( https://github.com/Spicord/Spicord/issues/46#issuecomment-926210844 )
