### ISSUE TITLE
The bot is ready but the message wont get send

### ISSUE THREAD

**Issue by Xintilsword** [OopsieWoopsie/Spicord#63]
![Screenshot_2022-07-31-18-27-59-44_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/108564217/182024222-5941b052-7328-4820-9c67-d7138846c379.jpg)
How do i fix this? I using bungeecord

**Comment by Xintilsword** [comment]
Same issues when try mute,unban,tempban dan unmute

**Comment by anvorgesa** [comment]
That can be caused because you are (probably) using another plugin which provides Discord integration (apart from Spicord)

**Comment by Xintilsword** [comment]
The bot is different with another bot i used for staff chat to discord

**Comment by anvorgesa** [comment]
Download and install this plugin on your server
https://github.com/Spicord/FindClass/releases/download/2.0/FindClass-2.0.jar

Then run on your server console `/findclass net.dv8tion.jda.api.JDA`

And you will see the list of plugins which may be causing the problem, you can also send me the command output because I'd like to know too.

**Comment by Xintilsword** [comment]
The command not working

**Comment by Xintilsword** [comment]
Wait
Oke

**Comment by Xintilsword** [comment]
The command won't work 
![Uploading Screenshot_2022-08-08-13-47-42-47_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()

**Comment by Xintilsword** [comment]
Even with the plugin findclass

**Comment by Xintilsword** [comment]
Same in the console the command not found

**Comment by anvorgesa** [comment]
You posted your comment too fast and the screenshot didn't had enough time to get uploaded. Please send it again and always sent the new errors you get even if you think they are the same as the previous one
