### ISSUE TITLE
Help with an error in the console (The person advised you)

### ISSUE THREAD

**Issue by karamzyatina** [OopsieWoopsie/Spicord#67]
Good afternoon! I was advised by @TrueMB. I get an error in the console when running Spicord JDA.
![opera_PlsNTkJ1md](https://user-images.githubusercontent.com/67735224/188152825-eb79068c-7817-4820-a1ed-3693ab757f16.png)
![opera_ZENO8zcyEL](https://user-images.githubusercontent.com/67735224/188152834-9fde80ea-5342-410b-abf8-8785278000f0.png)

**Comment by anvorgesa** [comment]
Hi, please post your full server log, otherwise I can't help

**Comment by anvorgesa** [comment]
I found your other issue that contained your server log.

The issue with you are having with Spicord is because you are using "snap" and it makes Spicord detect your server as BungeeCord instead of Velocity.

**Comment by karamzyatina** [comment]
thanks
