### ISSUE TITLE
kotlin

### ISSUE THREAD

**Issue by Michotek** [OopsieWoopsie/Spicord#74]
Is it possible to add compatiblity to EcoJobs plugin?

**Comment by anvorgesa** [comment]
First, the title is not related at all with what you are asking; and second, Spicord is a "Discord API provider" not a fully-featured plugin, it makes no sense to relate this plugin with a Jobs plugin at all.

**Comment by Michotek** [comment]
Oh, sorry. I was really tired while describing this topic. I meant, Spicord and EcoJobs both use Kotlin, and when both of those plugins are on the server, some functions aren't working. EcoJobs dev, told me to ask Spicord developers, to add compatibility to each other

**Comment by anvorgesa** [comment]
Oh, I understand now, but Spicord doesn't uses kotlin, and I don't even know the kotlin language :thinking:
