### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by Elixir121** [OopsieWoopsie/Spicord#80]
Hi! And there is integration for Spicord so that you can embed images in the BanAnnouncer plugin, so that when you write a ban, a full-size picture comes to the discord

**Comment by anvorgesa** [comment]
Hello, I guess you are talking about a kind of mix of the ProfileViewer addon with the BanAnnouncer addon, currently there's no public addon that can do exactly what you are asking for.

Here's how an image made by ProfileViewer looks like:
![image](https://github.com/Spicord/Spicord/assets/95182588/c9848ab4-8f77-49a2-850e-ad6d3a4641f3)

It could be interesting to experiment with the idea.
