### ISSUE TITLE
Can you post the permissions?

### ISSUE THREAD

**Issue by alexis-evelyn** [OopsieWoopsie/Spicord#9]
I found the permissions for the subcommands in the source code, but haven't found the one for the root /sp command. This looks like a promising plugin, so I'll definitely check it out, especially with the Bungeecord support. Thanks!

Edit: Hmmm, it appears the root command has it's permission set to null. Can we change that to be spicord.admin?

**Comment by OopsieWoopsie** [comment]
Hello, the root /sp command will only show the spicord version for those who doesn't have the spicord.admin permission, so I don't think it should have a special permission.
If you want to block users from running the /sp command you can just use a "Command Blocker" plugin

**Comment by alexis-evelyn** [comment]
That makes sense why it doesn't work. I had setup my permissions plugin to block all permissions except what is explicitly allowed. Thanks!
